name: Cypress Tests

on:
  push:
    branches: [ dev ]

jobs:
  cypress-run:
    name: Cypress build and Run
    defaults:
      run:
        working-directory: ./frontend/ 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.2 # use the explicit version number
        with:
          project: ./frontend/
          build: npm run build
          start: npm start